export const SERVICES_DETAIL = [
  {
    id: "pilot",
    slug: "pilot",
    name: "Implementation Pilot",
    tagline: "Test AI automation with minimal risk",
    price: "£1,500-2,000",
    priceQ1: "£1,500-2,000",
    priceQ2: "£1,500-2,000",
    timeline: "2-3 weeks",
    workflows: "2-3 core workflows",
    integrations: "2-3 systems",
    ideal: "First-time AI automation, proof of concept, testing the waters",
    color: "gray", // Not accent color
    icon: "Rocket",
    note: "Credit applied if upgraded within 60 days",
    deliverables: [
      "2-3 core workflow automations",
      "2-3 system integrations",
      "30-day monitoring period",
      "ROI report",
      "Expansion roadmap",
    ],
    features: {
      workflows: "2-3",
      integrations: "2-3",
      trainingPeriod: "30 days",
      customModels: true,
      multiModal: false,
      proactiveAlerts: false,
      dashboard: "Basic",
      support: "Optional",
    },
  },
  {
    id: "system",
    slug: "intelligent-automation-system",
    name: "Intelligent Automation System",
    tagline: "Automate 5-7 core workflows end-to-end",
    price: "£3,000-5,000",
    timeline: "4-8 weeks",
    workflows: "5-7 interconnected workflows",
    integrations: "5-8 systems",
    ideal: "Scaling operations, multiple interconnected workflows, comprehensive automation",
    color: "accent", // Wine-red
    icon: "Network",
    featured: true,
    note: "Includes 8-week optimization period",
    deliverables: [
      "5-7 interconnected workflows",
      "5-8 system integrations",
      "Performance dashboard",
      "8-week optimization period",
      "Monthly performance reports",
    ],
    features: {
      workflows: "5-7",
      integrations: "5-8",
      trainingPeriod: "8 weeks",
      customModels: true,
      multiModal: false,
      proactiveAlerts: true,
      dashboard: "Advanced",
      support: "Included",
    },
  },
  {
    id: "agent",
    slug: "custom-ai-agent",
    name: "Custom AI Agent",
    tagline: "Build AI that learns your business deeply",
    price: "£7,000-12,000",
    timeline: "6-10 weeks deployment + 90-day training",
    workflows: "Custom",
    integrations: "Unlimited",
    ideal: "Complex needs, deep learning required, autonomous decision-making",
    color: "white",
    icon: "Brain",
    note: "Continuous learning included for 90 days",
    deliverables: [
      "Bespoke AI entity",
      "Multi-modal integration (text, voice, data)",
      "Proactive alerting",
      "90-day training period",
      "Continuous learning system",
    ],
    features: {
      workflows: "Custom",
      integrations: "Unlimited",
      trainingPeriod: "90 days",
      customModels: true,
      multiModal: true,
      proactiveAlerts: true,
      dashboard: "Real-time",
      support: "Premium",
    },
  },
];

export const COMPARISON_FEATURES = [
  { id: "workflows", label: "Workflows Automated" },
  { id: "integrations", label: "System Integrations" },
  { id: "trainingPeriod", label: "Training & Optimization" },
  { id: "customModels", label: "Custom AI Models" },
  { id: "multiModal", label: "Multi-modal Input (Text, Voice, Data)" },
  { id: "proactiveAlerts", label: "Proactive Alerting" },
  { id: "dashboard", label: "Performance Dashboard" },
  { id: "support", label: "Ongoing Support" },
];

export const USE_CASES = [
  {
    id: "test",
    goal: "Test AI automation with minimal risk",
    recommendation: "pilot",
    reason: "Start with a focused pilot to prove ROI before full commitment.",
  },
  {
    id: "automate",
    goal: "Automate 5-7 core workflows end-to-end",
    recommendation: "system",
    reason: "Our Intelligent Automation System handles multiple interconnected workflows seamlessly.",
  },
  {
    id: "custom",
    goal: "Build a custom AI that learns our business deeply",
    recommendation: "agent",
    reason: "A Custom AI Agent provides autonomous reasoning trained on your proprietary knowledge.",
  },
  {
    id: "scale",
    goal: "Scale operations without hiring",
    recommendation: "system-or-agent",
    reason: "Depending on complexity: System for defined workflows, Agent for adaptive decision-making.",
  },
];

